version: 2

aliases:
  - &restore-cache
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
  - &install-deps
    run:
      name: Install Dependencies
      command: yarn install --ignore-scripts --frozen-lockfile --cache-folder ~/.cache/yarn
  - &build-packages
    run:
      name: Build
      command: yarn build
  - &save-cache
    save_cache:
      name: Save Yarn Package Cache
      key: yarn-packages-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn

jobs:
  build:
    working_directory: ~/notch
    docker:
      - image: cimg/node:21.7
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - *save-cache
      - run:
          name: Build
          command: yarn build

  tests:
    working_directory: ~/notch
    docker:
      - image: cimg/node:21.7
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - run:
          name: Tests (util)
          command: yarn test:util
      - run:
          name: Tests (express)
          command: yarn test:express
      - run:
          name: Tests (core)
          command: yarn test:core

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - tests:
          requires:
            - build
